"""Driver and gateway support for Siglent SPD3000-series power supplies."""

from .driver import SPD3000
from .exceptions import (
    GatewayAuthenticationError,
    GatewayConfigurationError,
    GatewayConnectionError,
    GatewayError,
    GatewayInternalError,
    GatewayProtocolError,
    GatewayVersionMismatchError,
    SPD3000CommandError,
    SPD3000ConnectionError,
    SPD3000DeferredResultError,
    SPD3000Error,
    SPD3000ProtocolError,
    SPD3000TimeoutError,
    SPD3000TimingWarning,
    SPD3000ValidationError,
    SPD3000VerificationError,
    UnknownModelError,
    UnsupportedFeatureError,
)
from .execution import (
    BatchResponses,
    BatchResult,
    CommandBatch,
    Deferred,
    DirectExecutor,
    ExecutionSettings,
    Query,
    Write,
)
from .gateway.config import load_gateway_auth
from .models import (
    Capabilities,
    Channel,
    ChannelStatus,
    ConnectionType,
    Identification,
    Model,
    NetworkSettings,
    OperatingMode,
    OutputState,
    RegulationMode,
    SystemError,
    SystemStatus,
    TimerState,
    TrackingMode,
    WaveformState,
)
from .scpi import Access, CommandInfo, iter_commands, lookup_command

__all__ = [
    "SPD3000",
    "Access",
    "BatchResponses",
    "BatchResult",
    "Capabilities",
    "Channel",
    "ChannelStatus",
    "CommandBatch",
    "CommandInfo",
    "ConnectionType",
    "Deferred",
    "DirectExecutor",
    "ExecutionSettings",
    "GatewayAuthenticationError",
    "GatewayConfigurationError",
    "GatewayConnectionError",
    "GatewayError",
    "GatewayInternalError",
    "GatewayProtocolError",
    "GatewayVersionMismatchError",
    "Identification",
    "Model",
    "NetworkSettings",
    "OperatingMode",
    "OutputState",
    "Query",
    "RegulationMode",
    "SPD3000CommandError",
    "SPD3000ConnectionError",
    "SPD3000DeferredResultError",
    "SPD3000Error",
    "SPD3000ProtocolError",
    "SPD3000TimeoutError",
    "SPD3000TimingWarning",
    "SPD3000ValidationError",
    "SPD3000VerificationError",
    "SystemError",
    "SystemStatus",
    "TimerState",
    "TrackingMode",
    "UnknownModelError",
    "UnsupportedFeatureError",
    "WaveformState",
    "Write",
    "iter_commands",
    "load_gateway_auth",
    "lookup_command",
]
