"""Driver and gateway support for Siglent SPD3000-series power supplies."""

from .driver import SPD3000
from .exceptions import (
    GatewayAuthenticationError,
    GatewayConnectionError,
    GatewayError,
    GatewayInternalError,
    GatewayProtocolError,
    GatewayVersionMismatchError,
    SPD3000CommandError,
    SPD3000ConnectionError,
    SPD3000Error,
    SPD3000ProtocolError,
    SPD3000TimeoutError,
    SPD3000TimingWarning,
    SPD3000ValidationError,
    UnknownModelError,
    UnsupportedFeatureError,
)
from .execution import (
    BatchResult,
    CommandBatch,
    DirectExecutor,
    ExecutionSettings,
    Query,
    Write,
)
from .models import (
    Capabilities,
    Channel,
    ChannelStatus,
    ConnectionType,
    Identification,
    Model,
    OperatingMode,
    RegulationMode,
    SystemError,
    SystemStatus,
    TrackingMode,
)
from .scpi import Access, CommandInfo, iter_commands, lookup_command

__all__ = [
    "SPD3000",
    "Access",
    "BatchResult",
    "Capabilities",
    "Channel",
    "ChannelStatus",
    "CommandBatch",
    "CommandInfo",
    "ConnectionType",
    "DirectExecutor",
    "ExecutionSettings",
    "GatewayAuthenticationError",
    "GatewayConnectionError",
    "GatewayError",
    "GatewayInternalError",
    "GatewayProtocolError",
    "GatewayVersionMismatchError",
    "Identification",
    "Model",
    "OperatingMode",
    "Query",
    "RegulationMode",
    "SPD3000CommandError",
    "SPD3000ConnectionError",
    "SPD3000Error",
    "SPD3000ProtocolError",
    "SPD3000TimeoutError",
    "SPD3000TimingWarning",
    "SPD3000ValidationError",
    "SystemError",
    "SystemStatus",
    "TrackingMode",
    "UnknownModelError",
    "UnsupportedFeatureError",
    "Write",
    "iter_commands",
    "lookup_command",
]
